### ISSUE TITLE
PMINet Reload Issue

### ISSUE THREAD

**Issue by SophieSarceau** [YangLing0818/IRDiff#2]
Dear authors, thanks for your amazing work!
When I was trying to reproduce the results based on this GitHub repo, I encountered an issue when reloading the pretrained PMINet weights, the warning indicated some mismatch between the pretrianed weights and the model architecture；
![image](https://github.com/user-attachments/assets/05f62fc2-27eb-4d75-873b-9ee850181fe7)
I'm wondering if I need to rename the keys like "ComplexesGraph.0.lin_src.weight" to "ComplexesGraph.0.lin.weight" to utilize the model weights fully.
Thanks for your attention, and looking forward to your reply.

**Comment by xzliu6** [comment]
How did you solve this problem? Thank you.

**Comment by SophieSarceau** [comment]
Please refer to this issue: https://github.com/YangLing0818/IPDiff/issues/2
The authors used torch-geometric version which is 2.0.4, you can check your version and see if things go well after this operation.

**Comment by xzliu6** [comment]
Wow, solved it, awesome! Thank you very much.
